name: Upload CSS Shortcuts to CDN
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish CSS Shortcuts"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  CDN_BUCKET: gc-design-system-production-cdn
  CDN_REGION: ca-central-1
  PACKAGE_NAME: '@gcds-core/css-shortcuts'

jobs:
  upload-to-cdn:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Configure AWS credentials using OIDC
        if: github.event.workflow_run.conclusion == 'success'
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          role-to-assume: arn:aws:iam::307395567143:role/gcds-utility-apply
          role-session-name: CDNPublish
          aws-region: ${{ env.CDN_REGION }}

      - name: Update CDN
        if: github.event.workflow_run.conclusion == 'success'
        run: |
          VERSION="$(cat package.json | jq -r .version)"
          PUBLISHED_PACKAGE="${{ env.PACKAGE_NAME }}@$VERSION"

          aws s3 sync ./dist s3://${{ env.CDN_BUCKET }}/"$PUBLISHED_PACKAGE"/dist --delete
          aws s3 sync ./dist s3://${{ env.CDN_BUCKET }}/${{ env.PACKAGE_NAME }}@latest/dist --delete
          aws s3api head-object --bucket ${{ env.CDN_BUCKET }} --key "$PUBLISHED_PACKAGE"/dist/gcds-css-shortcuts.css
          aws s3api head-object --bucket ${{ env.CDN_BUCKET }} --key ${{ env.PACKAGE_NAME }}@latest/dist/gcds-css-shortcuts.css

          aws cloudfront create-invalidation --distribution-id ${{ secrets.CDN_CLOUDFRONT_DIST_ID }} --paths "/*"

      - name: Slack notify on failure
        if: failure()
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Publish @gcds-core/css-shortcuts to CDN failed: <https://github.com/cds-snc/gcds-css-shortcuts/actions/workflows/upload-cdn.yml|Upload CSS Shortcuts to CDN>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ secrets.SLACK_WEBHOOK_OPS }}
